### ISSUE TITLE
Iconify sulist

### ISSUE THREAD

**Issue by hafizhasant** [Mahmud0808/Iconify#15]
**Describe the bug**
using Oneplus9pro nameless aosp rom with magisk delta and sulist enabled.after installin the the app and allowin root in sulist and after restartin the phone the app s stuck on main- screen (continue screen)

**Smartphone (please complete the following information):**
 - Device: _oneplus 9 pro
 - OS Name: _nameless aosp
 - Android Version: _Android 13
 - Iconify Version: _v2.0-Beta

**Additional context**
the app work on zygisk mode but doest work in sulist mode.

**Comment by Mahmud0808** [comment]
According to Magisk Delta documentation, [SuList cannot coexist with Zygisk. Modules functionality are less compatible. Most modules will not work or broken in SuList because of the way it works. Please don’t ask why some modules don’t work or system crashes.](https://huskydg.github.io/magisk-files/docs/sulist.html). And as Iconify is based on Magisk module to work properly, it can not work in SuList mode.
