### ISSUE TITLE
[FEATURE] Extend settings icons backround

### ISSUE THREAD

**Issue by Undisputed00x** [Mahmud0808/Iconify#181]
### Describe the feature

Been using the absolutely beautiful Gradicon icon pack with filled backround but the icon backround its applied only for settings home screen.
Can you add filled backround for the all the sub-settings pages ?

### Why would it be useful to add?

LineageOS 19.1 latest build
Android 12L
Poco x3 Pro

### Example(s)

Settings home screen: https://imgur.com/a/kkuYnKN
Missing icons backround example: https://imgur.com/a/DlC0meL
Missing icons backround example: https://imgur.com/a/vN7Gi9X

**Comment by Mahmud0808** [comment]
I skipped them because there are a lot of custom roms, each with their own icons added in different parts of settings. It is very hard for me to find every icon of every rom and create an svg/xml for them. So I just themed the icons of homepage of settings only. If you want fully themed icon everywhere, I think paid themes are a better option.
