### ISSUE TITLE
[FEATURE] Dark Time inside the colored Pill

### ISSUE THREAD

**Issue by srt54558** [Mahmud0808/Iconify#193]
### Describe the feature

![Screenshot_20230627-130546](https://github.com/Mahmud0808/Iconify/assets/90862487/fab6ac54-4122-4afd-8968-7b4444e60bd3)

The green pill is too bright with my Material you coloring. Of course i could change the color or change my background, but why? I love all other things by the look. Unfortunately the text color of the pill cant be changed as far as i know and i can not read it easily...
Maybe even a option to set a custom color only for he pill!

### Why would it be useful to add?

It would be useful because the Time would be easier to read on bright material you colors

### Example(s)

![Screenshot_20230627-130546](https://github.com/Mahmud0808/Iconify/assets/90862487/54cf37b7-90d1-4dd3-8a81-31cc577edb75)

Im quite bad with manipulating images, sorry. Imagine the purple to be the green

**Comment by Undisputed00x** [comment]
Same problem here i cant see the clock properly because the **monet tint** on clock is about the same as the clock chip theme.
Of course a easy fix would be to change the status bar theme but is not optimal.
Could be there an option to change only the status bar clock color when clock backround chip is enabled ?

![Screenshot_20230627-193654_Iconify (Debug)------](https://github.com/Mahmud0808/Iconify/assets/80290008/cb639192-4fdd-41b0-a15e-6aa0990a25ae)

**Comment by srt54558** [comment]
Good to know that other people have similar problems!
+the pill that can be selected in the QS is hardly readable!
![Screenshot_20230627-150231(1)](https://github.com/Mahmud0808/Iconify/assets/90862487/0e8985a2-47ca-4f57-8203-7497907b2a42)
