### ISSUE TITLE
[BUG] On higher blur instensity it looks terrible

### ISSUE THREAD

**Issue by tadekdudek** [Mahmud0808/Iconify#197]
### Describe the bug

See the screenshot

### Steps to reproduce

1. Enable window level blur
2. Set blur intensity to 100px
3. For example, QS panel looks terrible

### Expected behavior

OneUI has also high blur level, but doesn't look so...
[https://developer.samsung.com/one-ui/structure/visual-depth.html#Blur](https://developer.samsung.com/one-ui/structure/visual-depth.html#Blur)

### Screenshots

![Screenshot_20230628-113858_Iconify](https://github.com/Mahmud0808/Iconify/assets/99012892/6662a299-db41-4946-b918-4b13c3c03683)

### Device information

- Device: Redmi Note 7
- OS: LineageOS 20.0 (Android 13)
- App version: 6.2.0

**Comment by Mahmud0808** [comment]
This is not a bug, it's how Gaussian blur in AOSP works. Samsung, Xiaomi and other OEMs use different kind of blur implementations. AOSP uses gaussian blur because it's less resource hungry and thus can be used on large range of devices. I recommend to use low blur intensity. Higher blur intensity is added because of a user request (he likes the diamond effect with high blur intensity).
