### ISSUE TITLE
[BUG] "Switch" feature not working everywhere

### ISSUE THREAD

**Issue by goblin535353** [Mahmud0808/Iconify#210]
### Describe the bug

Hello. 

Not sure if bug, but the "Switch" feature not working everywhere. Some settings have the default switch, some have to custom switch.

Also, not sure if possible, but if we could please save and export entire current setup into a magisk module like the "Volume panel" feature does it, so we can just flash that one module. Currently this app installs hundrend overlays and it slows down my phone.

### Steps to reproduce

Steps to reproduce

### Expected behavior

Expected behavior

### Device information

OS: Los20
App version: latest

**Comment by Mahmud0808** [comment]
> Not sure if bug, but the "Switch" feature not working everywhere. Some settings have the default switch, some have to custom switch.

It's because iconify only replaces switch of Settings but some switches which you see are not changed are from SystemUI

Edit: Working on it.

> Also, not sure if possible, but if we could please save and export entire current setup into a magisk module like the "Volume panel" feature does it, so we can just flash that one module. Currently this app installs hundrend overlays and it slows down my phone.

It's indeed possible but complex work for me. Btw there's a guide [HERE](https://forum.xda-developers.com/t/android-theming-use-project-themer-iconify-without-adding-100-apks-to-you-device.4548123/) to remove the overlays which are not being used.
