### ISSUE TITLE
[BUG] QS tile styles crashes SystemUI

### ISSUE THREAD

**Issue by acwcanada** [Mahmud0808/Iconify#278]
### Describe the bug

Iconify 6.4 works great with A14 Beta 5.3 but it seems it is not compatible with the QPR1 Beta 1 even the newest v6.5. Not much to describe in this case. My Google Pixel 6 Pro with Android 14 QPR1 Beta 1 rooted with Magisk canary-26301, LSPosed 1.9.1 (6999)-Zygisk, setting up icon pack ok, setting up brightness bar ok, but once start to set up QS tile, Iconify crashed immediately and reboot into bootloops. I have to go into safe mode to disable the Iconify module. 

### Steps to reproduce

See above 

### Expected behavior

Expected to be working as in Android 14 Beta 5.3

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. v4.0-Beta]
Device: Google Pixel 6 Pro
OS: Android 14 QPR1 Beta 1

**Comment by Mahmud0808** [comment]
Can't do anything much until the source code is released or I get Android 14 QPR1 update for my emulators (as I do not own any pixel device).

**Comment by KenJyn76** [comment]
Hi! Commenting here after seeing #313, this seems to be for QS and that seems to be for the module. I pulled a log for the QS tile SystemUI crash. This is a clean Iconify install, with only the QS tile modification enabled. I have no other modifications beyond the latest of tools like Magisk, LSposed, Sui, on a Pixel 7 Pro on QPR1.

I put it in a pastebin because it seemed a little long to just be inline here.

https://pastebin.com/352xgJeJ

**Comment by lordofhype** [comment]
Hello!
Still relevant for A14 with January update

**Comment by HiFIi** [comment]
This project is dead

**Comment by Mahmud0808** [comment]
Fixed with latest v6.7.0
