### ISSUE TITLE
[FEATURE] Add back fingerprint icon

### ISSUE THREAD

**Issue by justtlouai** [Mahmud0808/Iconify#646]
### Describe the feature

Adding back the fingerprint icon to the inon packs, it's that simple.

### Why would it be useful to add?

more consistency across UI and customization 

### Example(s)

It used to be in the app, i see absolutely no reason why it would get removed.

**Comment by Mahmud0808** [comment]
The reason is that there are some codes in the fingerprint lottie icon which only works on latest version of lottie library. But crashes on ROMs which are still using older versions. And if I fix the codes of the icon, it works on older versions of lottie libraries but crashes on latest versions. There is no middle ground, either I make it usable on old versions or I make it compatible with latest versions. Both has 50-50 chance of crashing SystemUI. So the only solution was to remove it altogether which has 0 chance of crashing SystemUI.

**Comment by justtlouai** [comment]
Can't it be optional then? Or maybe automatically disable it if the device is running an older ROM ?

**Comment by Mahmud0808** [comment]
Icon packs are simple overlays, not xposed module. So there is no way for it to know the library version or if it will even crash.
